config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :publications

  root 'publications#index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'La publicación fue exitosamente creada.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'La publicación fue exitosamente actualizada.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'La publicación fue exitosamente eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:Precio, :Titulo, :Descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YapoCl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%>
<% end %>
<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Hola mundo</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Precio %><br>
    <%= f.text_field :Precio %>
  </div>
  <div class="field">
    <%= f.label :Titulo %><br>
    <%= f.text_field :Titulo %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :Descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editar Publicación</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @publication %> |
<%= link_to 'Atrás', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de publicaciones</h1>

<table>
  <thead>
    <tr>
      <th>Precio</th>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.Precio %></td>
        <td><%= publication.Titulo %></td>
        <td><%= publication.Descripcion %></td>
        <td><%= link_to 'Mostrar', publication %></td>
        <td><%= link_to 'Editar', edit_publication_path(publication) %></td>
        <td><%= link_to 'Eliminar', publication, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>Nueva publicación</h1>

<%= render 'form' %>

<%= link_to 'Atrás', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Precio:</strong>
  <%= @publication.Precio %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @publication.Titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @publication.Descripcion %>
</p>

<%= link_to 'Editar', edit_publication_path(@publication) %> |
<%= link_to 'Atrás', publications_path %>